modified the yaml for the artifacts to be uploaded

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,4 +1,4 @@
-name: Playwright Tests
+name: Playwright Testing
 
 on:
   push:
@@ -32,17 +32,20 @@ jobs:
       - name: Install Allure CLI
         run: npm install -g allure-commandline
 
-      - name: Generate Allure report
-        run: allure generate allure-results  --clean -o allure-report
+      - name: List contents of allure-results directory (debug)
+        run: ls -R allure-results || echo "Directory allure-results not found"
 
-      - name: List the contents of the allure-report directory
+      - name: Generate Allure report
+        run: allure generate allure-results --clean -o allure-report
+
+      - name: List contents of allure-report directory (debug)
         run: ls -R allure-report || echo "Directory allure-report not found"
 
       - name: Upload Allure report as artifact
         uses: actions/upload-artifact@v3
         with:
           name: allure-report
-          path: allure-report
+          path: allure-report/
 
       - name: Display Allure report link
         run: |
